import React from 'react';

function HomePage() {
  return (
    <div style={{ textAlign: 'left', maxWidth: '800px' }}>
      <h1 style={{ color: 'var(--primary-color)' }}>NeuroScan: AI-Assisted Diagnosis Tool</h1>
      
      <div style={{ padding: '1rem', border: '1px solid #e02828', borderRadius: '5px', backgroundColor: 'rgba(224, 40, 40, 0.1)', marginBottom: '2rem' }}>
        <h2 style={{ marginTop: 0 }}>Important Disclaimer</h2>
        <p>
          <strong>This tool is for informational and assistive purposes only.</strong> The predictions generated by the AI model are intended to help accelerate the diagnosis process for qualified medical professionals.
        </p>
        <p>
          It must <strong>not</strong> be used as a sole method for clinical diagnosis or for making treatment decisions. All results must be verified by a certified radiologist or physician. The creators of this tool are not liable for any decisions made based on its output.
        </p>
      </div>

      <h3>How It Works</h3>
      <p>
        This application utilizes an advanced deep learning model (ResNet-50) trained on a large dataset of brain MRI scans to classify potential tumors. The process is simple:
      </p>
      <ol>
        <li><strong>Upload an Image:</strong> Navigate to the "Predict" page and upload a clear, high-quality brain MRI scan.</li>
        <li><strong>AI Analysis:</strong> Our model processes the image, identifying key features and patterns to classify it into categories such as glioma, meningioma, or no tumor.</li>
        <li><strong>Receive Results:</strong> You will receive a prediction, a confidence score, and a Grad-CAM heatmap overlay. This heatmap visualizes the areas of the MRI that the model focused on to make its decision.</li>
      </ol>

      <h3>Getting Started</h3>
      <ul>
        <li>Use the <strong>Predict</strong> page to analyze a new MRI scan.</li>
        <li>Visit your <strong>Account</strong> page at any time to review your complete history of past predictions and view the corresponding overlay images.</li>
      </ul>
    </div>
  );
}

export default HomePage;